apiVersion: apps/v1
kind: Deployment
metadata:
  # this is for logging / debugging
  name: ps-deployment
spec:
  # how many instances
  replicas: 1
  # this matches the pod label
  selector:
    matchLabels:
      component: ps
  # this describes the pod definition
  template:
    metadata:
      labels:
        component: ps
    spec:
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: ps-volume-claim
      containers:
        - name: ps
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
              subPath: postgres
