version: "3"
services:
  db:
    image: postgres:latest
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./api/pgdata:/var/lib/postgresql/data
  redis:
    image: redis:latest
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    depends_on:
      - api
      - web
    ports:
      - "3050:80"
  web:
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./web:/app
    environment:
      - USE_STAGING=false
      - LOCAL_URL=http://192.168.0.106:3050
      - STAGING_URL=http://journal-env.rcpv566ppp.eu-west-2.elasticbeanstalk.com
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    depends_on:
      - db
    volumes:
      - /app/node_modules
      - ./api:/app
    environment:
      - REDISHOST=redis
      - REDISPORT=6379
      - PGUSER=postgres
      - PGHOST=db
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
      - SALT=1
      - ACCESS_TOKEN_SECRET=secret
      - ACCESS_TOKEN_EXPIRY=10d
      - REFRESH_TOKEN_SECRET=secret
      - REFRESH_TOKEN_EXPIRY=10d
      - LOCAL_URL=http://192.168.0.106:3050
